---
name: "Deployment AMI via packer"

on:
  push:
    branches:
      - developement

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET}}
      AWS_DEFAULT_REGION: ${{ secrets.DEV_REGION }}
      packer_version: "1.9.4"

    steps:
  
      - name: "Date"
        run: date
        
      - name: "OS"
        run : cat /etc/issue

      - name: "checkout repo"
        uses: actions/checkout@v3

      - name: "Packer Installation"
        uses: hashicorp/setup-packer@main  
        with:
          version: ${{ env.packer_version }}

      - name: "Packer Init"
        run: packer init .
        working-directory: ./packer/

      - name: "Packer validate"
        run: packer validate -var-file="dev.pkrvars.hcl" .
        working-directory: ./packer/

      - name: "Packer Format"
        run: packer fmt .
        working-directory: ./packer/

      - name: "Packer Build"
        run: packer build -var-file="dev.pkrvars.hcl" .
        working-directory: ./packer/
